# Generated by Django 2.2.1 on 2019-05-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sandwich',
            options={'ordering': ('created',), 'verbose_name_plural': 'sandwiches'},
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='base',
            field=models.IntegerField(choices=[(1, 'Turkey'), (2, 'Roast Beef'), (3, 'Veggie')], default=1, max_length=20),
        ),
    ]
