# Generated by Django 2.2.1 on 2019-05-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sandwich_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='extra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
