# Generated by Django 2.2.1 on 2019-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_topping_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='base',
            field=models.IntegerField(choices=[(1, 'Turkey'), (2, 'Roast Beef'), (3, 'Veggie')], default=1),
        ),
    ]
