# Generated by Django 2.2.1 on 2019-05-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190525_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='toppings',
            field=models.ManyToManyField(to='api.Topping'),
        ),
    ]
